### PR TITLE
Improve geographies handling

### PR DESCRIPTION
**Pull request by pronebird**
This PR adds a little logic around XHR fetching and fixes couple of existing issues:

1. Makes geography data passed in props available immediately. Previously there would be no data until `componentDidMount` which caused the first render pass to happen with empty geographies. (#51)

2. Better XHR handling, particularly fixes the issue with XHR request running after the component is unmounted.

3. Covers #49

### CODE REVIEW

**Comment by pronebird** [comment]
@zimrick I think you've merged master on top of my changes. I rebased my branch meanwhile.

**Comment by zimrick** [comment]
This is strange. When I look at the original files changed in your PR it seems that that duplication exists there... I've reverted the merge for now. I may have messed up something here though, so any help on how to resolve this is much appreciated. This is good work.

**Comment by pronebird** [comment]
Sure. I'll rebase and send a separate PR

**Comment by pronebird** [comment]
Please take a look at #57 . I looked at diff in split view and for sure don't see `fetchGeographies` defined twice. I tested it once again on my mac and everything seems to work fine too. Please pull the branch and test it too if you can just in case so we don't break the master.

**Pull request merged**
