### PR TITLE
add CustomZoomableGroup

### PR DESCRIPTION
**Pull request by lostfictions**
Adds `<CustomZoomableGroup>` as suggested in #188.

Unfortunately it looks like there's no tests, no linting, and the documentation website is private? So I'm not sure if I can do better than this -- hopefully whoever is in charge of the website can document its existence if this PR is accepted.

### CODE REVIEW

**Comment by TiagoRechau** [comment]
@zimrick is there any chance of having this merged? Thanks!

**Comment by kopach** [comment]
IMHO, this PR isn't relevant anymore. see my comment here https://github.com/zcreativelabs/react-simple-maps/issues/188#issuecomment-870748365

**Comment by lostfictions** [comment]
I'll close it, then -- I migrated away from this library last year soon after posting this, so don't have time to keep up with developments. Hopefully someone else can pick up this PR if it's still relevant!

**Comment by kopach** [comment]
thanks @lostfictions. Just out of curiosity, which library you use now?

**Pull request closed without merging**
