### PR TITLE
Address high vulnerability issue

### PR DESCRIPTION
**Pull request by wmhartl**
Address issue #302 

- push package updates for d3
- fix a couple of dev dependencies so tests and builds work again

### CODE REVIEW

**Comment by wmhartl** [comment]
Hi @zimrick - any feedback or thoughts about getting this merged?

**Comment by wmhartl** [comment]
Hi @zimrick thoughts on this? This hanging vulnerability is problematic.

**Comment by vikdiesel** [comment]
Hi @zimrick,
Do you think this problem is fixable somehow? Thank you

**Comment by wmhartl** [comment]
It's been nearly two months - any thoughts here @zimrick?

**Comment by gbanis** [comment]
It would be great to merge this so we don't have to start forking to address the vulnerability 🙏

**Comment by ivan-penchev** [comment]
Hi @zimrick  this starts to be flagged by snyk and other dependancy platforms. If the fix is so easy, can we get it in?

**Comment by jbouhier** [comment]
@zimrick Can we merge this PR, please?

**Comment by jbouhier** [comment]
## Workaround with your package manager of choice

- **npm / yarn v1**: [patch-package](https://www.npmjs.com/package/patch-package)
- **yarn v2+**: [yarn patch](https://yarnpkg.com/cli/patch)
- **pnpm:** [pnpm patch](https://pnpm.io/cli/patch)

## Yarn v2+:
- Run `yarn patch react-simple-maps`
- It will extract the dependency in a separate folder
- Apply the [changes contained in this PR](https://github.com/zcreativelabs/react-simple-maps/pull/321/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
- Run `yarn patch-commit -s </path/to/temp/folder>`

Et voila!

**Comment by wmhartl** [comment]
hi @zimrick - thanks so much for merging this! I hope you'll cut a new minor release (e.g. 3.0.1) so npm, snyk, etc, all pick up the changes you've merged. Really appreciate the package!

**Comment by zimrick** [comment]
Hi @wmhartl,
The changes are already public in 4.0.0 (`npm install react-simple-maps@beta`). The reason this is a bit tricky is because the updated versions of the d3 modules caused some issues when using react-simple-maps in next.js.

**Comment by joey-ma-steelgem** [comment]
Next.js user here and am patiently waiting for stable 4.0 😅

**Pull request merged**
