### PR TITLE
New Line Component

### PR DESCRIPTION
**Pull request by sorodrigo**
Hello there 👋 !
This PR includes a new `<Line />` component that let's the user draw lines and add event listeners to it. It's 100% based of the implementation of `<Marker />`, I thought that sticking to the way that marker was implemented would make it easier to merge into this project. The original implementation is for another project where this use case was needed. In lieau of a linter I left the changes that my company's eslint + prettier setup demanded. If something doesn't comply with your code style I'm willing to adapt it.

The generic implementation draws straight lines, I used it for drawing arcs such as flight paths (or country commodity exports in my case) but figured that letting the user customise the path from outside was better.

Here's a GIF of what can be achieved with this.
map block

To draw a curved line aka Arc the user just needs to provide a drawing function like the following:
```js
buildCurves(start, end, arc) {
    const x0 = start[0];
    const x1 = end[0];
    const y0 = start[1];
    const y1 = end[1];
    const curve = {
      pointOfControlUp: `${x1} ${y0}`,
      pointOfControlDown: `${x0} ${y1}`
    }[arc.curveStyle];

    return `M ${start.join(' ')} Q ${curve} ${end.join(' ')}`;
  }
```
This way any other Path compatible implementations are possible!

P.S. If you're interested in merging this I can also write some documentation. Just felt that writing it before you even approved the feature wasn't very wise.

### CODE REVIEW

**Comment by zimrick** [comment]
This looks really awesome @sorodrigo! Will have a proper look at the code tomorrow.

**Comment by zimrick** [comment]
Sorry it took a while. This is really cool. It's nice that the API is very close to that of `Markers`. It would be really cool if you could help with the documentation for this.

I will do some refactoring before pushing a new version, since there's quite some repetition building up with `Markers`, `Annotations`, and `Lines`, so maybe time to move some stuff into a more generic `Group` component and leaving those three (`Markers`, `Annotations`, `Lines`) as thin named wrappers for it.

**Comment by sorodrigo** [comment]
I’m glad you liked it. Yes I actually thought the same thing about `markers` And `lines` and was planning PR’ing this next. So totally agree. Right now I’m on holidays but will add docs asap. Also I can help with the refactor if you need help. Finally I strongly advise introducing some code quality tools, this project is great and growing. Eslint and prettier can help you grow faster and safer IMHO. I also could help you out set this up.

**Comment by zimrick** [comment]
Yup, very good points with eslint and prettier. Would be happy to get your help with that. 
Enjoy your holidays in the meantime :)

**Comment by ansumanshah** [comment]
Hey thanks for this, is there an example repo to refer?

**Comment by zimrick** [comment]
There is no dedicated example for this yet in the repo. Docs and examples will be coming soon though.

**Pull request merged**
