### PR TITLE
Adds support for direct object imports to be passed to Geographies

### PR DESCRIPTION
**Pull request by jamestthompson3**
One problem I was having was the latency of making a request for my topojson file causing slow render times for my map. To solve this, I added the option of passing an topojson object directly to the `Geographies` component.

Example:
```
import mapData from './world-50m-with-data.json'

instantiate parent component, etc...

 <ComposableMap
            projectionConfig={{ scale: 215, rotation: [-10,0,0] }}
            projection='miller'
            width={1400}
            height={790}
            style={{
              width: '100%',
              height: '100%',
              zIndex: '100'
            }}
            aspectRatio='none'
          >
            <ZoomableGroup center={[10, 0]} zoom={1} disablePanning={true}>
              <Geographies geography={mapData}>

... rest of map
```

This renders much faster and could be useful for those who aren't using excessively large topojson files.

### CODE REVIEW

**Comment by jamestthompson3** [comment]
Also adds the option for a custom viewBox on the composableMap element

**Comment by walidvb** [comment]
Thanks, could be useful to me. Would be nice to update the README to reflect these changes, too :)

**Comment by jamestthompson3** [comment]
@walidvb  I will update the README

**Comment by zimrick** [comment]
This is cool. It is technically possible to avoid the load by using `geographyPaths` and doing the topojson conversion yourself using `topojson-client`, but this would simplify this step by using the internal conversion mechanism that is already used when loading the data from a url.

So with your solution we can now feed either a url or topojson directly to `react-simple-maps`. For those who need more control `geographyPaths` can still provide an interface to feed the array directly and bypass the topojson stuff. Did I understand that correctly?

The only downside is that we are renaming the prop from `geographyUrl` to `geography`. Ideally it would be good to merge all three (geographyUrl, geography, geographyPaths) into one prop (`geography`).

**Comment by jamestthompson3** [comment]
I agree. I can work on that if you would prefer to wait until three are merged into one path before closing this PR.

**Comment by jamestthompson3** [comment]
If the changes are alright, then I would like to make a motion to merge them.

**Comment by zimrick** [comment]
Thanks for the great work @jamestthompson3, really appreciate it. Will play around with this a little bit before we go to v.0.10. I am wondering whether some in code disclaimer would be a good thing to alert devs to the change... Will probably also have another look at the readme to make sure the changes are highlighted.

**Pull request merged**
